language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose up --build -d
  - docker exec -it education-platform-for-pythoneers-app bash -c "python manage.py test"

notifications:
  email:
    on_error: never
    on_failure: never
    on_start: never
    on_cancel: never